---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
- instances: 1
  name: minio-server
  networks:
  - name: minio1
  persistent_disk: 0
  resource_pool: small_z1
  templates:
  - name: minio-server
    release: minio

networks: (( param "Please configure the global network definitions for this Deployment" ))

properties:
  minio:
    access_key: "defaultaccesskey"
    secret_key: "defaultsecretkey"
    port:       "9001"